export const DOCUMENT_TYPES = {
  FACTURA_OPERACION_INTERNA: '01',
  FACTURA_IMPORTACION: '02',
  FACTURA_EXPORTACION: '03',
  NOTA_CREDITO_REFERENTE_FE: '04',
  NOTA_DEBITO_REFERENTE_FE: '05',
  NOTA_CREDITO_GENERICA: '06',
  NOTA_DEBITO_GENERICA: '07',
  FACTURA_ZONA_FRANCA: '08',
  REEMBOLSO: '09',
  COMPROBANTE_COMPRA: '10',
} as const;

export type DocumentType = typeof DOCUMENT_TYPES[keyof typeof DOCUMENT_TYPES];
