export const EMISSION_TYPES = {
  AUTORIZACION_PREVIA_NORMAL: '01',
  AUTORIZACION_PREVIA_CONTINGENCIA: '02',
  AUTORIZACION_POSTERIOR_NORMAL: '03',
  AUTORIZACION_POSTERIOR_CONTINGENCIA: '04',
} as const;

export type EmissionType = typeof EMISSION_TYPES[keyof typeof EMISSION_TYPES];
