export const NATURE_OPERATIONS = {
  VENTA: '01',
  EXPORTACION: '02',
  RE_EXPORTACION: '03',
  VENTA_FUENTE_EXTRANJERA: '04',
  TRANSFERENCIA_TRASPASO: '10',
  DEVOLUCION: '11',
  CONSIGNACION: '12',
  REMESA: '13',
  ENTREGA_GRATUITA: '14',
  COMPRA: '20',
  IMPORTACION: '21',
} as const;

export type NatureOperation = typeof NATURE_OPERATIONS[keyof typeof NATURE_OPERATIONS];
