export const OTI_CODES = {
  SUME_911: '01',
  PORTABILIDAD_NUMERICA: '02',
  SEGURO_5_PERCENT: '03',
  SEGURO_AUTOS_1_PERCENT: '04',
  SALIDA_AEROPUERTO: '05',
  DESARROLLO_AEROPUERTO: '06',
  SEGURIDAD_AEROPUERTO: '07',
  OTROS_CARGOS: '08',
  COMBUSTIBLE: '09',
  FECI: '10',
  INTERESES: '11',
} as const;

export type OTICode = typeof OTI_CODES[keyof typeof OTI_CODES];
